#include <actor/MapActor.h>
#include <actor/ProfileID.h>

const sead::UnsafeArray<s32, 724> MapActor::cProfileID = {
    ProfileID::c1D3,                            //   0
    ProfileID::c1D5,                            //   1
    ProfileID::c1DF,                            //   2
    ProfileID::c1E0,                            //   3
    ProfileID::c1E1,                            //   4
    ProfileID::c1E2,                            //   5
    ProfileID::c1E3,                            //   6
    ProfileID::c1E4,                            //   7
    ProfileID::c1E5,                            //   8
    ProfileID::c1E6,                            //   9
    ProfileID::c1E7,                            //  10
    ProfileID::c1E8,                            //  11
    ProfileID::c1E9,                            //  12
    ProfileID::c1EA,                            //  13
    ProfileID::c1EC,                            //  14
    ProfileID::c1EF,                            //  15
    ProfileID::c1F0,                            //  16
    ProfileID::c1F1,                            //  17
    ProfileID::c1F2,                            //  18
    ProfileID::c200,                            //  19
    ProfileID::c203,                            //  20
    ProfileID::c204,                            //  21
    ProfileID::c17D,                            //  22
    ProfileID::c205,                            //  23
    ProfileID::c206,                            //  24
    ProfileID::c235,                            //  25
    ProfileID::c23F,                            //  26
    ProfileID::c242,                            //  27
    ProfileID::c243,                            //  28
    ProfileID::c244,                            //  29
    ProfileID::c245,                            //  30
    ProfileID::c113,                            //  31
    ProfileID::c2E4,                            //  32
    ProfileID::c232,                            //  33
    ProfileID::c233,                            //  34
    ProfileID::c259,                            //  35
    ProfileID::c000,                            //  36
    ProfileID::c001,                            //  37
    ProfileID::c002,                            //  38
    ProfileID::c003,                            //  39
    ProfileID::c004,                            //  40
    ProfileID::c005,                            //  41
    ProfileID::c008,                            //  42
    ProfileID::c009,                            //  43
    ProfileID::c2EE,                            //  44
    ProfileID::c1AA,                            //  45
    ProfileID::c1AB,                            //  46
    ProfileID::c1AD,                            //  47
    ProfileID::c1AE,                            //  48
    ProfileID::c076,                            //  49
    ProfileID::c077,                            //  50
    ProfileID::c262,                            //  51
    ProfileID::c0BF,                            //  52
    ProfileID::c225,                            //  53
    ProfileID::c2F3,                            //  54
    ProfileID::c201,                            //  55
    ProfileID::c227,                            //  56
    ProfileID::c224,                            //  57
    ProfileID::c232,                            //  58
    ProfileID::c121,                            //  59
    ProfileID::c123,                            //  60
    ProfileID::c126,                            //  61
    ProfileID::c306,                            //  62
    ProfileID::c1F3,                            //  63
    ProfileID::c1F4,                            //  64
    ProfileID::c18B,                            //  65
    ProfileID::c18E,                            //  66
    ProfileID::c264,                            //  67
    ProfileID::c027,                            //  68
    ProfileID::c028,                            //  69
    ProfileID::c00B,                            //  70
    ProfileID::c03C,                            //  71
    ProfileID::c040,                            //  72
    ProfileID::c189,                            //  73
    ProfileID::c207,                            //  74
    ProfileID::c2FB,                            //  75
    ProfileID::c2F5,                            //  76
    ProfileID::c2FD,                            //  77
    ProfileID::c2F7,                            //  78
    ProfileID::c2F9,                            //  79
    ProfileID::c036,                            //  80
    ProfileID::c038,                            //  81
    ProfileID::c307,                            //  82
    ProfileID::c308,                            //  83
    ProfileID::c309,                            //  84
    ProfileID::c22C,                            //  85
    ProfileID::c17F,                            //  86
    ProfileID::c195,                            //  87
    ProfileID::c054,                            //  88
    ProfileID::c055,                            //  89
    ProfileID::c056,                            //  90
    ProfileID::c057,                            //  91
    ProfileID::c058,                            //  92
    ProfileID::c059,                            //  93
    ProfileID::c052,                            //  94
    ProfileID::c053,                            //  95
    ProfileID::c265,                            //  96
    ProfileID::cBgCenter,                       //  97
    ProfileID::c266,                            //  98
    ProfileID::c181,                            //  99
    ProfileID::c00D,                            // 100
    ProfileID::c212,                            // 101
    ProfileID::c24C,                            // 102
    ProfileID::c070,                            // 103
    ProfileID::c158,                            // 104
    ProfileID::c159,                            // 105
    ProfileID::c21E,                            // 106
    ProfileID::c25A,                            // 107
    ProfileID::c25B,                            // 108
    ProfileID::c25C,                            // 109
    ProfileID::c25E,                            // 110
    ProfileID::c260,                            // 111
    ProfileID::c071,                            // 112
    ProfileID::c214,                            // 113
    ProfileID::c223,                            // 114
    ProfileID::c2EB,                            // 115
    ProfileID::c029,                            // 116
    ProfileID::c02B,                            // 117
    ProfileID::c02A,                            // 118
    ProfileID::c26C,                            // 119
    ProfileID::c21B,                            // 120
    ProfileID::c313,                            // 121
    ProfileID::c315,                            // 122
    ProfileID::c079,                            // 123
    ProfileID::c07A,                            // 124
    ProfileID::c274,                            // 125
    ProfileID::c275,                            // 126
    ProfileID::c276,                            // 127
    ProfileID::c277,                            // 128
    ProfileID::c21C,                            // 129
    ProfileID::c271,                            // 130
    ProfileID::c221,                            // 131
    ProfileID::c081,                            // 132
    ProfileID::c0B8,                            // 133
    ProfileID::c316,                            // 134
    ProfileID::c27B,                            // 135
    ProfileID::c27C,                            // 136
    ProfileID::c288,                            // 137
    ProfileID::c289,                            // 138
    ProfileID::c14F,                            // 139
    ProfileID::c150,                            // 140
    ProfileID::c14E,                            // 141
    ProfileID::c14D,                            // 142
    ProfileID::c1C2,                            // 143
    ProfileID::c1B9,                            // 144
    ProfileID::c0BE,                            // 145
    ProfileID::c08F,                            // 146
    ProfileID::c128,                            // 147
    ProfileID::c129,                            // 148
    ProfileID::c196,                            // 149
    ProfileID::c0A8,                            // 150
    ProfileID::c0AA,                            // 151
    ProfileID::c183,                            // 152
    ProfileID::c0BB,                            // 153
    ProfileID::c136,                            // 154
    ProfileID::c091,                            // 155
    ProfileID::c07B,                            // 156
    ProfileID::c320,                            // 157
    ProfileID::c19B,                            // 158
    ProfileID::c08B,                            // 159
    ProfileID::c08C,                            // 160
    ProfileID::c08D,                            // 161
    ProfileID::c08E,                            // 162
    ProfileID::c07C,                            // 163
    ProfileID::c209,                            // 164
    ProfileID::c02D,                            // 165
    ProfileID::c02E,                            // 166
    ProfileID::c1A9,                            // 167
    ProfileID::c00E,                            // 168
    ProfileID::c00F,                            // 169
    ProfileID::c20A,                            // 170
    ProfileID::c065,                            // 171
    ProfileID::c066,                            // 172
    ProfileID::c067,                            // 173
    ProfileID::c068,                            // 174
    ProfileID::c20C,                            // 175
    ProfileID::c072,                            // 176
    ProfileID::c073,                            // 177
    ProfileID::c074,                            // 178
    ProfileID::c273,                            // 179
    ProfileID::c27D,                            // 180
    ProfileID::c27F,                            // 181
    ProfileID::c0D3,                            // 182
    ProfileID::c30A,                            // 183
    ProfileID::c15E,                            // 184
    ProfileID::c30B,                            // 185
    ProfileID::c0D4,                            // 186
    ProfileID::c28B,                            // 187
    ProfileID::c0C1,                            // 188
    ProfileID::c138,                            // 189
    ProfileID::c12C,                            // 190
    ProfileID::c12E,                            // 191
    ProfileID::c0D7,                            // 192
    ProfileID::c0D9,                            // 193
    ProfileID::c231,                            // 194
    ProfileID::c141,                            // 195
    ProfileID::c011,                            // 196
    ProfileID::c319,                            // 197
    ProfileID::c317,                            // 198
    ProfileID::c184,                            // 199
    ProfileID::c050,                            // 200
    ProfileID::c318,                            // 201
    ProfileID::c185,                            // 202
    ProfileID::c186,                            // 203
    ProfileID::c28C,                            // 204
    ProfileID::c137,                            // 205
    ProfileID::cBun,                            // 206
    ProfileID::c080,                            // 207
    ProfileID::c13A,                            // 208
    ProfileID::c13B,                            // 209
    ProfileID::c04D,                            // 210
    ProfileID::c102,                            // 211
    ProfileID::c248,                            // 212
    ProfileID::c0EE,                            // 213
    ProfileID::c02F,                            // 214
    ProfileID::c22B,                            // 215
    ProfileID::cBunDemo,                        // 216
    ProfileID::c03D,                            // 217
    ProfileID::c30C,                            // 218
    ProfileID::c30D,                            // 219
    ProfileID::c30E,                            // 220
    ProfileID::c30F,                            // 221
    ProfileID::c0C2,                            // 222
    ProfileID::cBunW2,                          // 223
    ProfileID::c1C0,                            // 224
    ProfileID::cBunW6,                          // 225
    ProfileID::c163,                            // 226
    ProfileID::c164,                            // 227
    ProfileID::c05F,                            // 228
    ProfileID::c311,                            // 229
    ProfileID::cLarry,                          // 230
    ProfileID::c165,                            // 231
    ProfileID::c0C8,                            // 232
    ProfileID::c12A,                            // 233
    ProfileID::c12B,                            // 234
    ProfileID::c177,                            // 235
    ProfileID::c179,                            // 236
    ProfileID::c2EC,                            // 237
    ProfileID::c033,                            // 238
    ProfileID::c0AD,                            // 239
    ProfileID::c0DE,                            // 240
    ProfileID::c0C5,                            // 241
    ProfileID::c0C6,                            // 242
    ProfileID::c1BF,                            // 243
    ProfileID::cKokoopaSearchFire,              // 244
    ProfileID::cKokoopaDemo,                    // 245
    ProfileID::cBunW4,                          // 246
    ProfileID::c1D6,                            // 247
    ProfileID::c0C7,                            // 248
    ProfileID::c1FC,                            // 249
    ProfileID::c098,                            // 250
    ProfileID::c0EC,                            // 251
    ProfileID::c0F0,                            // 252
    ProfileID::c31E,                            // 253
    ProfileID::c31D,                            // 254
    ProfileID::c1D7,                            // 255
    ProfileID::c09A,                            // 256
    ProfileID::c0C9,                            // 257
    ProfileID::c0CA,                            // 258
    ProfileID::c1F6,                            // 259
    ProfileID::c075,                            // 260
    ProfileID::c0CD,                            // 261
    ProfileID::c0CE,                            // 262
    ProfileID::c117,                            // 263
    ProfileID::c07E,                            // 264
    ProfileID::c035,                            // 265
    ProfileID::c09E,                            // 266
    ProfileID::c31F,                            // 267
    ProfileID::c11B,                            // 268
    ProfileID::c0D0,                            // 269
    ProfileID::c2FF,                            // 270
    ProfileID::c093,                            // 271
    ProfileID::c094,                            // 272
    ProfileID::c095,                            // 273
    ProfileID::c0A2,                            // 274
    ProfileID::c062,                            // 275
    ProfileID::c229,                            // 276
    ProfileID::c197,                            // 277
    ProfileID::c0DC,                            // 278
    ProfileID::c198,                            // 279
    ProfileID::c05C,                            // 280
    ProfileID::c199,                            // 281
    ProfileID::c278,                            // 282
    ProfileID::c034,                            // 283
    ProfileID::c0CB,                            // 284
    ProfileID::c0CC,                            // 285
    ProfileID::c28E,                            // 286
    ProfileID::c166,                            // 287
    ProfileID::c2F4,                            // 288
    ProfileID::c0E0,                            // 289
    ProfileID::c0E1,                            // 290
    ProfileID::c014,                            // 291
    ProfileID::c0E2,                            // 292
    ProfileID::c0E3,                            // 293
    ProfileID::c0E5,                            // 294
    ProfileID::c0E4,                            // 295
    ProfileID::cLemmy,                          // 296
    ProfileID::c031,                            // 297
    ProfileID::c161,                            // 298
    ProfileID::c167,                            // 299
    ProfileID::c168,                            // 300
    ProfileID::c1FE,                            // 301
    ProfileID::cBunW3,                          // 302
    ProfileID::c303,                            // 303
    ProfileID::c0E9,                            // 304
    ProfileID::c29E,                            // 305
    ProfileID::c162,                            // 306
    ProfileID::c0EA,                            // 307
    ProfileID::c0E7,                            // 308
    ProfileID::c0E8,                            // 309
    ProfileID::c29F,                            // 310
    ProfileID::c037,                            // 311
    ProfileID::c05D,                            // 312
    ProfileID::c323,                            // 313
    ProfileID::c0EB,                            // 314
    ProfileID::c0E6,                            // 315
    ProfileID::c099,                            // 316
    ProfileID::cBunW5,                          // 317
    ProfileID::c28F,                            // 318
    ProfileID::c0B2,                            // 319
    ProfileID::c292,                            // 320
    ProfileID::c22A,                            // 321
    ProfileID::c325,                            // 322
    ProfileID::c187,                            // 323
    ProfileID::c0B3,                            // 324
    ProfileID::c19E,                            // 325
    ProfileID::c19D,                            // 326
    ProfileID::c0A7,                            // 327
    ProfileID::c19F,                            // 328
    ProfileID::c236,                            // 329
    ProfileID::c0B4,                            // 330
    ProfileID::c237,                            // 331
    ProfileID::c238,                            // 332
    ProfileID::c239,                            // 333
    ProfileID::c20D,                            // 334
    ProfileID::c20F,                            // 335
    ProfileID::c2A2,                            // 336
    ProfileID::c2A1,                            // 337
    ProfileID::c144,                            // 338
    ProfileID::c0F1,                            // 339
    ProfileID::c1A0,                            // 340
    ProfileID::c326,                            // 341
    ProfileID::c23A,                            // 342
    ProfileID::c23B,                            // 343
    ProfileID::c249,                            // 344
    ProfileID::c0F3,                            // 345
    ProfileID::c304,                            // 346
    ProfileID::c0F5,                            // 347
    ProfileID::c0F8,                            // 348
    ProfileID::c0F4,                            // 349
    ProfileID::c096,                            // 350
    ProfileID::c1F9,                            // 351
    ProfileID::c2A4,                            // 352
    ProfileID::c032,                            // 353
    ProfileID::c0FA,                            // 354
    ProfileID::cFloorHoleDokan,                 // 355
    ProfileID::c0FB,                            // 356
    ProfileID::c28D,                            // 357
    ProfileID::c0B0,                            // 358
    ProfileID::c0FC,                            // 359
    ProfileID::c0B1,                            // 360
    ProfileID::c015,                            // 361
    ProfileID::c305,                            // 362
    ProfileID::c327,                            // 363
    ProfileID::c23C,                            // 364
    ProfileID::c1C1,                            // 365
    ProfileID::c016,                            // 366
    ProfileID::c16B,                            // 367
    ProfileID::cMorton,                         // 368
    ProfileID::c1B4,                            // 369
    ProfileID::c1A3,                            // 370
    ProfileID::c097,                            // 371
    ProfileID::c100,                            // 372
    ProfileID::c064,                            // 373
    ProfileID::c321,                            // 374
    ProfileID::c322,                            // 375
    ProfileID::c049,                            // 376
    ProfileID::c03B,                            // 377
    ProfileID::c32C,                            // 378
    ProfileID::c32F,                            // 379
    ProfileID::c13C,                            // 380
    ProfileID::c17A,                            // 381
    ProfileID::c293,                            // 382
    ProfileID::cWendy,                          // 383
    ProfileID::c24E,                            // 384
    ProfileID::cLudwig,                         // 385
    ProfileID::c18D,                            // 386
    ProfileID::c331,                            // 387
    ProfileID::c103,                            // 388
    ProfileID::cRoy,                            // 389
    ProfileID::c09B,                            // 390
    ProfileID::c09D,                            // 391
    ProfileID::cUnderwaterKoopaJr,              // 392
    ProfileID::c16D,                            // 393
    ProfileID::c330,                            // 394
    ProfileID::c04F,                            // 395
    ProfileID::c104,                            // 396
    ProfileID::c131,                            // 397
    ProfileID::c132,                            // 398
    ProfileID::cUnderwaterKoopaJr,              // 399
    ProfileID::c061,                            // 400
    ProfileID::c01A,                            // 401
    ProfileID::c2EF,                            // 402
    ProfileID::cIggy,                           // 403
    ProfileID::c157,                            // 404
    ProfileID::c042,                            // 405
    ProfileID::cBossKK,                         // 406
    ProfileID::c05A,                            // 407
    ProfileID::c33E,                            // 408
    ProfileID::c16E,                            // 409
    ProfileID::c0FE,                            // 410
    ProfileID::cKameck,                         // 411
    ProfileID::cKameckDemo,                     // 412
    ProfileID::c1CB,                            // 413
    ProfileID::cKokoopaShipLemmy,               // 414
    ProfileID::cKokoopaShipMorton,              // 415
    ProfileID::cWakiSearchMagKiller,            // 416
    ProfileID::cKokoopaShipLarry,               // 417
    ProfileID::cKokoopaShipWendy,               // 418
    ProfileID::cKokoopaShipIggy,                // 419
    ProfileID::cKokoopaShipRoy,                 // 420
    ProfileID::cKokoopaShipLudwig,              // 421
    ProfileID::c13D,                            // 422
    ProfileID::c018,                            // 423
    ProfileID::cKokoopaShipWarpCannon,          // 424
    ProfileID::c107,                            // 425
    ProfileID::c1D2,                            // 426
    ProfileID::c11D,                            // 427
    ProfileID::c0FF,                            // 428
    ProfileID::c043,                            // 429
    ProfileID::c03F,                            // 430
    ProfileID::c03E,                            // 431
    ProfileID::cKoopaJrDemo,                    // 432
    ProfileID::cBoxingKoopaJr,                  // 433
    ProfileID::c0A3,                            // 434
    ProfileID::cBossKKDemo,                     // 435
    ProfileID::c05E,                            // 436
    ProfileID::c1D3,                            // 437
    ProfileID::c1D3,                            // 438
    ProfileID::c0A1,                            // 439
    ProfileID::c23D,                            // 440
    ProfileID::c284,                            // 441
    ProfileID::c294,                            // 442
    ProfileID::c210,                            // 443
    ProfileID::c11E,                            // 444
    ProfileID::c33F,                            // 445
    ProfileID::c286,                            // 446
    ProfileID::c2A5,                            // 447
    ProfileID::c32E,                            // 448
    ProfileID::c328,                            // 449
    ProfileID::cKameckIceConfig,                // 450
    ProfileID::c1C8,                            // 451
    ProfileID::c1C5,                            // 452
    ProfileID::c148,                            // 453
    ProfileID::c149,                            // 454
    ProfileID::c010,                            // 455
    ProfileID::cKameckWarpPos,                  // 456
    ProfileID::c05B,                            // 457
    ProfileID::c088,                            // 458
    ProfileID::cPeachFinalCastleKoopaJr,        // 459
    ProfileID::c01D,                            // 460
    ProfileID::c01E,                            // 461
    ProfileID::cKoopa,                          // 462
    ProfileID::c15C,                            // 463
    ProfileID::c108,                            // 464
    ProfileID::c143,                            // 465
    ProfileID::cKoopaDemo,                      // 466
    ProfileID::cKoopaShutter,                   // 467
    ProfileID::cKoopaFireWaki,                  // 468
    ProfileID::cPeach,                          // 469
    ProfileID::c2F0,                            // 470
    ProfileID::c1D8,                            // 471
    ProfileID::c1D9,                            // 472
    ProfileID::cFinalKoopa,                     // 473
    ProfileID::c33C,                            // 474
    ProfileID::c13E,                            // 475
    ProfileID::c202,                            // 476
    ProfileID::cFinalKoopaJr,                   // 477
    ProfileID::c174,                            // 478
    ProfileID::c04A,                            // 479
    ProfileID::c1B3,                            // 480
    ProfileID::c1F8,                            // 481
    ProfileID::c21A,                            // 482
    ProfileID::c178,                            // 483
    ProfileID::c030,                            // 484
    ProfileID::c044,                            // 485
    ProfileID::c31A,                            // 486
    ProfileID::c24A,                            // 487
    ProfileID::c295,                            // 488
    ProfileID::c10A,                            // 489
    ProfileID::c10B,                            // 490
    ProfileID::cPeachFinalCastleKoopaJrLift,    // 491
    ProfileID::cPeachFinalCastleKoopaJrLiftHmove, // 492
    ProfileID::c03A,                            // 493
    ProfileID::cUnderwaterKoopaJrRetreatPos,    // 494
    ProfileID::c020,                            // 495
    ProfileID::c1A5,                            // 496
    ProfileID::cFinalKoopaDemo,                 // 497
    ProfileID::c18A,                            // 498
    ProfileID::c04B,                            // 499
    ProfileID::c300,                            // 500
    ProfileID::c013,                            // 501
    ProfileID::c301,                            // 502
    ProfileID::c114,                            // 503
    ProfileID::c232,                            // 504
    ProfileID::c233,                            // 505
    ProfileID::c0B5,                            // 506
    ProfileID::cShootingStar,                   // 507
    ProfileID::c101,                            // 508
    ProfileID::c155,                            // 509
    ProfileID::c156,                            // 510
    ProfileID::c086,                            // 511
    ProfileID::c0A6,                            // 512
    ProfileID::c340,                            // 513
    ProfileID::c341,                            // 514
    ProfileID::c045,                            // 515
    ProfileID::c082,                            // 516
    ProfileID::c083,                            // 517
    ProfileID::c084,                            // 518
    ProfileID::c085,                            // 519
    ProfileID::c15D,                            // 520
    ProfileID::c342,                            // 521
    ProfileID::c0DF,                            // 522
    ProfileID::c140,                            // 523
    ProfileID::c047,                            // 524
    ProfileID::c133,                            // 525
    ProfileID::c134,                            // 526
    ProfileID::cPeachDemo,                      // 527
    ProfileID::c343,                            // 528
    ProfileID::c2A3,                            // 529
    ProfileID::c0AE,                            // 530
    ProfileID::c345,                            // 531
    ProfileID::cRoyLiftWaki,                    // 532
    ProfileID::cWendyIcicle,                    // 533
    ProfileID::c0D5,                            // 534
    ProfileID::c0D6,                            // 535
    ProfileID::c268,                            // 536
    ProfileID::cSpanner,                        // 537
    ProfileID::c118,                            // 538
    ProfileID::c17B,                            // 539
    ProfileID::c051,                            // 540
    ProfileID::c267,                            // 541
    ProfileID::c04C,                            // 542
    ProfileID::c1CE,                            // 543
    ProfileID::c04E,                            // 544
    ProfileID::c2A0,                            // 545
    ProfileID::c2E9,                            // 546
    ProfileID::cQuestPrizeItem,                 // 547
    ProfileID::c0BC,                            // 548
    ProfileID::c046,                            // 549
    ProfileID::c1EB,                            // 550
    ProfileID::c119,                            // 551
    ProfileID::c1F7,                            // 552
    ProfileID::c16C,                            // 553
    ProfileID::c346,                            // 554
    ProfileID::c17C,                            // 555
    ProfileID::c348,                            // 556
    ProfileID::c022,                            // 557
    ProfileID::cPeachFinalCastleKoopaJrDemo,    // 558
    ProfileID::c1CA,                            // 559
    ProfileID::cWendyFloor,                     // 560
    ProfileID::c31B,                            // 561
    ProfileID::c039,                            // 562
    ProfileID::c041,                            // 563
    ProfileID::c24D,                            // 564
    ProfileID::c28A,                            // 565
    ProfileID::c0B7,                            // 566
    ProfileID::c230,                            // 567
    ProfileID::c296,                            // 568
    ProfileID::c1C9,                            // 569
    ProfileID::c024,                            // 570
    ProfileID::c2E3,                            // 571
    ProfileID::c2EA,                            // 572
    ProfileID::c0DA,                            // 573
    ProfileID::c087,                            // 574
    ProfileID::c152,                            // 575
    ProfileID::c151,                            // 576
    ProfileID::c153,                            // 577
    ProfileID::c154,                            // 578
    ProfileID::c281,                            // 579
    ProfileID::c282,                            // 580
    ProfileID::c069,                            // 581
    ProfileID::c06A,                            // 582
    ProfileID::c06B,                            // 583
    ProfileID::c145,                            // 584
    ProfileID::c0F2,                            // 585
    ProfileID::c222,                            // 586
    ProfileID::c21D,                            // 587
    ProfileID::c216,                            // 588
    ProfileID::c217,                            // 589
    ProfileID::c218,                            // 590
    ProfileID::c219,                            // 591
    ProfileID::c21F,                            // 592
    ProfileID::c299,                            // 593
    ProfileID::c29C,                            // 594
    ProfileID::c1D4,                            // 595
    ProfileID::c32D,                            // 596
    ProfileID::c220,                            // 597
    ProfileID::c0B6,                            // 598
    ProfileID::c2F2,                            // 599
    ProfileID::c14B,                            // 600
    ProfileID::c1D0,                            // 601
    ProfileID::c0EF,                            // 602
    ProfileID::c314,                            // 603
    ProfileID::cBoxingKoopaJrPostBattleDemo,    // 604
    ProfileID::cBoxingKoopaJrClownPostBattleDemo, // 605
    ProfileID::c17E,                            // 606
    ProfileID::c1AC,                            // 607
    ProfileID::c351,                            // 608
    ProfileID::cIggyRoom,                       // 609
    ProfileID::c31C,                            // 610
    ProfileID::c1FB,                            // 611
    ProfileID::c11C,                            // 612
    ProfileID::c089,                            // 613
    ProfileID::c08A,                            // 614
    ProfileID::c213,                            // 615
    ProfileID::c026,                            // 616
    ProfileID::c1B8,                            // 617
    ProfileID::c0F6,                            // 618
    ProfileID::c0F7,                            // 619
    ProfileID::c226,                            // 620
    ProfileID::c228,                            // 621
    ProfileID::c352,                            // 622
    ProfileID::c241,                            // 623
    ProfileID::c012,                            // 624
    ProfileID::c0AF,                            // 625
    ProfileID::c29A,                            // 626
    ProfileID::cPeachFinalCastleKoopaJrLiftPairObj, // 627
    ProfileID::c01F,                            // 628
    ProfileID::c272,                            // 629
    ProfileID::c115,                            // 630
    ProfileID::c116,                            // 631
    ProfileID::c0DD,                            // 632
    ProfileID::c169,                            // 633
    ProfileID::c0F9,                            // 634
    ProfileID::c25F,                            // 635
    ProfileID::c25D,                            // 636
    ProfileID::c261,                            // 637
    ProfileID::c298,                            // 638
    ProfileID::c1C7,                            // 639
    ProfileID::c22D,                            // 640
    ProfileID::c16F,                            // 641
    ProfileID::c00C,                            // 642
    ProfileID::c290,                            // 643
    ProfileID::c291,                            // 644
    ProfileID::c09C,                            // 645
    ProfileID::c06C,                            // 646
    ProfileID::c06D,                            // 647
    ProfileID::c06E,                            // 648
    ProfileID::c06F,                            // 649
    ProfileID::c1AF,                            // 650
    ProfileID::c27E,                            // 651
    ProfileID::c0CF,                            // 652
    ProfileID::c279,                            // 653
    ProfileID::c1D1,                            // 654
    ProfileID::c0C4,                            // 655
    ProfileID::c240,                            // 656
    ProfileID::c2E0,                            // 657
    ProfileID::c0DB,                            // 658
    ProfileID::c234,                            // 659
    ProfileID::c006,                            // 660
    ProfileID::c29B,                            // 661
    ProfileID::c2F1,                            // 662
    ProfileID::c18C,                            // 663
    ProfileID::c297,                            // 664
    ProfileID::c1B0,                            // 665
    ProfileID::c14A,                            // 666
    ProfileID::c092,                            // 667
    ProfileID::c10C,                            // 668
    ProfileID::c048,                            // 669
    ProfileID::c019,                            // 670
    ProfileID::c0C0,                            // 671
    ProfileID::c14C,                            // 672
    ProfileID::c2ED,                            // 673
    ProfileID::c0FD,                            // 674
    ProfileID::c0D1,                            // 675
    ProfileID::c063,                            // 676
    ProfileID::c344,                            // 677
    ProfileID::c127,                            // 678
    ProfileID::c090,                            // 679
    ProfileID::c0AC,                            // 680
    ProfileID::c2E5,                            // 681
    ProfileID::c1F5,                            // 682
    ProfileID::c122,                            // 683
    ProfileID::c246,                            // 684
    ProfileID::c247,                            // 685
    ProfileID::c15A,                            // 686
    ProfileID::c20B,                            // 687
    ProfileID::c146,                            // 688
    ProfileID::c023,                            // 689
    ProfileID::c2E7,                            // 690
    ProfileID::c2E8,                            // 691
    ProfileID::c124,                            // 692
    ProfileID::c02C,                            // 693
    ProfileID::c0A0,                            // 694
    ProfileID::c182,                            // 695
    ProfileID::c09F,                            // 696
    ProfileID::c147,                            // 697
    ProfileID::c1ED,                            // 698
    ProfileID::c0B9,                            // 699
    ProfileID::c0BA,                            // 700
    ProfileID::c125,                            // 701
    ProfileID::c1FD,                            // 702
    ProfileID::c310,                            // 703
    ProfileID::c12F,                            // 704
    ProfileID::c07D,                            // 705
    ProfileID::c130,                            // 706
    ProfileID::c12D,                            // 707
    ProfileID::c347,                            // 708
    ProfileID::c0A4,                            // 709
    ProfileID::c15B,                            // 710
    ProfileID::c0A5,                            // 711
    ProfileID::c1EE,                            // 712
    ProfileID::c180,                            // 713
    ProfileID::c060,                            // 714
    ProfileID::c007,                            // 715
    ProfileID::c312,                            // 716
    ProfileID::c0C3,                            // 717
    ProfileID::c1B7,                            // 718
    ProfileID::c0A9,                            // 719
    ProfileID::c0AB,                            // 720
    ProfileID::c1B1,                            // 721
    ProfileID::c2E6,                            // 722
    ProfileID::c215                             // 723
};
