#include <actor/MapActor.h>
#include <actor/ProfileInfo.h>

const MapActor::Profile MapActor::cProfileID[] = {
    ProfileInfo::cProfileID_1D3,                                        //   0
    ProfileInfo::cProfileID_1D5,                                        //   1
    ProfileInfo::cProfileID_1DF,                                        //   2
    ProfileInfo::cProfileID_1E0,                                        //   3
    ProfileInfo::cProfileID_1E1,                                        //   4
    ProfileInfo::cProfileID_1E2,                                        //   5
    ProfileInfo::cProfileID_1E3,                                        //   6
    ProfileInfo::cProfileID_1E4,                                        //   7
    ProfileInfo::cProfileID_1E5,                                        //   8
    ProfileInfo::cProfileID_1E6,                                        //   9
    ProfileInfo::cProfileID_1E7,                                        //  10
    ProfileInfo::cProfileID_1E8,                                        //  11
    ProfileInfo::cProfileID_1E9,                                        //  12
    ProfileInfo::cProfileID_1EA,                                        //  13
    ProfileInfo::cProfileID_1EC,                                        //  14
    ProfileInfo::cProfileID_1EF,                                        //  15
    ProfileInfo::cProfileID_1F0,                                        //  16
    ProfileInfo::cProfileID_1F1,                                        //  17
    ProfileInfo::cProfileID_1F2,                                        //  18
    ProfileInfo::cProfileID_Nokonoko,                                   //  19
    ProfileInfo::cProfileID_203,                                        //  20
    ProfileInfo::cProfileID_204,                                        //  21
    ProfileInfo::cProfileID_17D,                                        //  22
    ProfileInfo::cProfileID_205,                                        //  23
    ProfileInfo::cProfileID_206,                                        //  24
    ProfileInfo::cProfileID_235,                                        //  25
    ProfileInfo::cProfileID_23F,                                        //  26
    ProfileInfo::cProfileID_242,                                        //  27
    ProfileInfo::cProfileID_243,                                        //  28
    ProfileInfo::cProfileID_244,                                        //  29
    ProfileInfo::cProfileID_245,                                        //  30
    ProfileInfo::cProfileID_113,                                        //  31
    ProfileInfo::cProfileID_2E4,                                        //  32
    ProfileInfo::cProfileID_232,                                        //  33
    ProfileInfo::cProfileID_233,                                        //  34
    ProfileInfo::cProfileID_259,                                        //  35
    ProfileInfo::cProfileID_000,                                        //  36
    ProfileInfo::cProfileID_001,                                        //  37
    ProfileInfo::cProfileID_002,                                        //  38
    ProfileInfo::cProfileID_003,                                        //  39
    ProfileInfo::cProfileID_004,                                        //  40
    ProfileInfo::cProfileID_005,                                        //  41
    ProfileInfo::cProfileID_008,                                        //  42
    ProfileInfo::cProfileID_009,                                        //  43
    ProfileInfo::cProfileID_2EE,                                        //  44
    ProfileInfo::cProfileID_1AA,                                        //  45
    ProfileInfo::cProfileID_1AB,                                        //  46
    ProfileInfo::cProfileID_1AD,                                        //  47
    ProfileInfo::cProfileID_1AE,                                        //  48
    ProfileInfo::cProfileID_076,                                        //  49
    ProfileInfo::cProfileID_077,                                        //  50
    ProfileInfo::cProfileID_262,                                        //  51
    ProfileInfo::cProfileID_0BF,                                        //  52
    ProfileInfo::cProfileID_225,                                        //  53
    ProfileInfo::cProfileID_2F3,                                        //  54
    ProfileInfo::cProfileID_201,                                        //  55
    ProfileInfo::cProfileID_227,                                        //  56
    ProfileInfo::cProfileID_224,                                        //  57
    ProfileInfo::cProfileID_232,                                        //  58
    ProfileInfo::cProfileID_121,                                        //  59
    ProfileInfo::cProfileID_ActorBlockRenga,                            //  60
    ProfileInfo::cProfileID_126,                                        //  61
    ProfileInfo::cProfileID_306,                                        //  62
    ProfileInfo::cProfileID_1F3,                                        //  63
    ProfileInfo::cProfileID_1F4,                                        //  64
    ProfileInfo::cProfileID_ActorCoin,                                  //  65
    ProfileInfo::cProfileID_18E,                                        //  66
    ProfileInfo::cProfileID_264,                                        //  67
    ProfileInfo::cProfileID_027,                                        //  68
    ProfileInfo::cProfileID_028,                                        //  69
    ProfileInfo::cProfileID_00B,                                        //  70
    ProfileInfo::cProfileID_PairObjChild,                               //  71
    ProfileInfo::cProfileID_040,                                        //  72
    ProfileInfo::cProfileID_189,                                        //  73
    ProfileInfo::cProfileID_207,                                        //  74
    ProfileInfo::cProfileID_2FB,                                        //  75
    ProfileInfo::cProfileID_2F5,                                        //  76
    ProfileInfo::cProfileID_2FD,                                        //  77
    ProfileInfo::cProfileID_2F7,                                        //  78
    ProfileInfo::cProfileID_2F9,                                        //  79
    ProfileInfo::cProfileID_036,                                        //  80
    ProfileInfo::cProfileID_038,                                        //  81
    ProfileInfo::cProfileID_307,                                        //  82
    ProfileInfo::cProfileID_308,                                        //  83
    ProfileInfo::cProfileID_309,                                        //  84
    ProfileInfo::cProfileID_22C,                                        //  85
    ProfileInfo::cProfileID_17F,                                        //  86
    ProfileInfo::cProfileID_195,                                        //  87
    ProfileInfo::cProfileID_054,                                        //  88
    ProfileInfo::cProfileID_055,                                        //  89
    ProfileInfo::cProfileID_056,                                        //  90
    ProfileInfo::cProfileID_057,                                        //  91
    ProfileInfo::cProfileID_058,                                        //  92
    ProfileInfo::cProfileID_059,                                        //  93
    ProfileInfo::cProfileID_052,                                        //  94
    ProfileInfo::cProfileID_053,                                        //  95
    ProfileInfo::cProfileID_265,                                        //  96
    ProfileInfo::cProfileID_BgCenter,                                   //  97
    ProfileInfo::cProfileID_266,                                        //  98
    ProfileInfo::cProfileID_181,                                        //  99
    ProfileInfo::cProfileID_00D,                                        // 100
    ProfileInfo::cProfileID_212,                                        // 101
    ProfileInfo::cProfileID_24C,                                        // 102
    ProfileInfo::cProfileID_070,                                        // 103
    ProfileInfo::cProfileID_SwitchHatenaButton,                         // 104
    ProfileInfo::cProfileID_SwitchPbutton,                              // 105
    ProfileInfo::cProfileID_21E,                                        // 106
    ProfileInfo::cProfileID_25A,                                        // 107
    ProfileInfo::cProfileID_25B,                                        // 108
    ProfileInfo::cProfileID_25C,                                        // 109
    ProfileInfo::cProfileID_25E,                                        // 110
    ProfileInfo::cProfileID_260,                                        // 111
    ProfileInfo::cProfileID_071,                                        // 112
    ProfileInfo::cProfileID_214,                                        // 113
    ProfileInfo::cProfileID_223,                                        // 114
    ProfileInfo::cProfileID_2EB,                                        // 115
    ProfileInfo::cProfileID_029,                                        // 116
    ProfileInfo::cProfileID_02B,                                        // 117
    ProfileInfo::cProfileID_02A,                                        // 118
    ProfileInfo::cProfileID_26C,                                        // 119
    ProfileInfo::cProfileID_21B,                                        // 120
    ProfileInfo::cProfileID_313,                                        // 121
    ProfileInfo::cProfileID_315,                                        // 122
    ProfileInfo::cProfileID_Intermittent,                               // 123
    ProfileInfo::cProfileID_IntermittentPermanent,                      // 124
    ProfileInfo::cProfileID_274,                                        // 125
    ProfileInfo::cProfileID_275,                                        // 126
    ProfileInfo::cProfileID_SearchKiller,                               // 127
    ProfileInfo::cProfileID_277,                                        // 128
    ProfileInfo::cProfileID_21C,                                        // 129
    ProfileInfo::cProfileID_271,                                        // 130
    ProfileInfo::cProfileID_221,                                        // 131
    ProfileInfo::cProfileID_081,                                        // 132
    ProfileInfo::cProfileID_LineSpinLift,                               // 133
    ProfileInfo::cProfileID_316,                                        // 134
    ProfileInfo::cProfileID_27B,                                        // 135
    ProfileInfo::cProfileID_27C,                                        // 136
    ProfileInfo::cProfileID_288,                                        // 137
    ProfileInfo::cProfileID_289,                                        // 138
    ProfileInfo::cProfileID_14F,                                        // 139
    ProfileInfo::cProfileID_ObjPipeDown,                                // 140
    ProfileInfo::cProfileID_14E,                                        // 141
    ProfileInfo::cProfileID_14D,                                        // 142
    ProfileInfo::cProfileID_1C2,                                        // 143
    ProfileInfo::cProfileID_1B9,                                        // 144
    ProfileInfo::cProfileID_0BE,                                        // 145
    ProfileInfo::cProfileID_08F,                                        // 146
    ProfileInfo::cProfileID_128,                                        // 147
    ProfileInfo::cProfileID_129,                                        // 148
    ProfileInfo::cProfileID_196,                                        // 149
    ProfileInfo::cProfileID_0A8,                                        // 150
    ProfileInfo::cProfileID_0AA,                                        // 151
    ProfileInfo::cProfileID_183,                                        // 152
    ProfileInfo::cProfileID_0BB,                                        // 153
    ProfileInfo::cProfileID_136,                                        // 154
    ProfileInfo::cProfileID_091,                                        // 155
    ProfileInfo::cProfileID_WaterIntermittent,                          // 156
    ProfileInfo::cProfileID_320,                                        // 157
    ProfileInfo::cProfileID_19B,                                        // 158
    ProfileInfo::cProfileID_08B,                                        // 159
    ProfileInfo::cProfileID_08C,                                        // 160
    ProfileInfo::cProfileID_08D,                                        // 161
    ProfileInfo::cProfileID_08E,                                        // 162
    ProfileInfo::cProfileID_WaterIntermittentPermanent,                 // 163
    ProfileInfo::cProfileID_209,                                        // 164
    ProfileInfo::cProfileID_02D,                                        // 165
    ProfileInfo::cProfileID_02E,                                        // 166
    ProfileInfo::cProfileID_BlueCoin,                                   // 167
    ProfileInfo::cProfileID_00E,                                        // 168
    ProfileInfo::cProfileID_00F,                                        // 169
    ProfileInfo::cProfileID_20A,                                        // 170
    ProfileInfo::cProfileID_KillerHoudai,                               // 171
    ProfileInfo::cProfileID_StretchKillerHoudai,                        // 172
    ProfileInfo::cProfileID_MagnumKillerHoudai,                         // 173
    ProfileInfo::cProfileID_MagnumKillerHoudaiDown,                     // 174
    ProfileInfo::cProfileID_MechaKoopa,                                 // 175
    ProfileInfo::cProfileID_072,                                        // 176
    ProfileInfo::cProfileID_073,                                        // 177
    ProfileInfo::cProfileID_074,                                        // 178
    ProfileInfo::cProfileID_273,                                        // 179
    ProfileInfo::cProfileID_27D,                                        // 180
    ProfileInfo::cProfileID_27F,                                        // 181
    ProfileInfo::cProfileID_0D3,                                        // 182
    ProfileInfo::cProfileID_30A,                                        // 183
    ProfileInfo::cProfileID_IcicleBig,                                  // 184
    ProfileInfo::cProfileID_30B,                                        // 185
    ProfileInfo::cProfileID_0D4,                                        // 186
    ProfileInfo::cProfileID_28B,                                        // 187
    ProfileInfo::cProfileID_0C1,                                        // 188
    ProfileInfo::cProfileID_138,                                        // 189
    ProfileInfo::cProfileID_12C,                                        // 190
    ProfileInfo::cProfileID_12E,                                        // 191
    ProfileInfo::cProfileID_0D7,                                        // 192
    ProfileInfo::cProfileID_0D9,                                        // 193
    ProfileInfo::cProfileID_FireSnake,                                  // 194
    ProfileInfo::cProfileID_141,                                        // 195
    ProfileInfo::cProfileID_011,                                        // 196
    ProfileInfo::cProfileID_319,                                        // 197
    ProfileInfo::cProfileID_317,                                        // 198
    ProfileInfo::cProfileID_184,                                        // 199
    ProfileInfo::cProfileID_050,                                        // 200
    ProfileInfo::cProfileID_318,                                        // 201
    ProfileInfo::cProfileID_185,                                        // 202
    ProfileInfo::cProfileID_186,                                        // 203
    ProfileInfo::cProfileID_28C,                                        // 204
    ProfileInfo::cProfileID_137,                                        // 205
    ProfileInfo::cProfileID_Bun,                                        // 206
    ProfileInfo::cProfileID_YoganIntermittent,                          // 207
    ProfileInfo::cProfileID_13A,                                        // 208
    ProfileInfo::cProfileID_13B,                                        // 209
    ProfileInfo::cProfileID_KinokoLift,                                 // 210
    ProfileInfo::cProfileID_102,                                        // 211
    ProfileInfo::cProfileID_248,                                        // 212
    ProfileInfo::cProfileID_TarzanIvy,                                  // 213
    ProfileInfo::cProfileID_02F,                                        // 214
    ProfileInfo::cProfileID_22B,                                        // 215
    ProfileInfo::cProfileID_BunDemo,                                    // 216
    ProfileInfo::cProfileID_03D,                                        // 217
    ProfileInfo::cProfileID_30C,                                        // 218
    ProfileInfo::cProfileID_30D,                                        // 219
    ProfileInfo::cProfileID_30E,                                        // 220
    ProfileInfo::cProfileID_30F,                                        // 221
    ProfileInfo::cProfileID_SnakeBlock,                                 // 222
    ProfileInfo::cProfileID_BunW2,                                      // 223
    ProfileInfo::cProfileID_1C0,                                        // 224
    ProfileInfo::cProfileID_BunW6,                                      // 225
    ProfileInfo::cProfileID_163,                                        // 226
    ProfileInfo::cProfileID_164,                                        // 227
    ProfileInfo::cProfileID_05F,                                        // 228
    ProfileInfo::cProfileID_311,                                        // 229
    ProfileInfo::cProfileID_Larry,                                      // 230
    ProfileInfo::cProfileID_165,                                        // 231
    ProfileInfo::cProfileID_0C8,                                        // 232
    ProfileInfo::cProfileID_12A,                                        // 233
    ProfileInfo::cProfileID_12B,                                        // 234
    ProfileInfo::cProfileID_FireBar,                                    // 235
    ProfileInfo::cProfileID_179,                                        // 236
    ProfileInfo::cProfileID_2EC,                                        // 237
    ProfileInfo::cProfileID_033,                                        // 238
    ProfileInfo::cProfileID_0AD,                                        // 239
    ProfileInfo::cProfileID_0DE,                                        // 240
    ProfileInfo::cProfileID_0C5,                                        // 241
    ProfileInfo::cProfileID_0C6,                                        // 242
    ProfileInfo::cProfileID_1BF,                                        // 243
    ProfileInfo::cProfileID_KokoopaSearchFire,                          // 244
    ProfileInfo::cProfileID_KokoopaDemo,                                // 245
    ProfileInfo::cProfileID_BunW4,                                      // 246
    ProfileInfo::cProfileID_1D6,                                        // 247
    ProfileInfo::cProfileID_0C7,                                        // 248
    ProfileInfo::cProfileID_1FC,                                        // 249
    ProfileInfo::cProfileID_098,                                        // 250
    ProfileInfo::cProfileID_0EC,                                        // 251
    ProfileInfo::cProfileID_0F0,                                        // 252
    ProfileInfo::cProfileID_31E,                                        // 253
    ProfileInfo::cProfileID_31D,                                        // 254
    ProfileInfo::cProfileID_1D7,                                        // 255
    ProfileInfo::cProfileID_09A,                                        // 256
    ProfileInfo::cProfileID_0C9,                                        // 257
    ProfileInfo::cProfileID_0CA,                                        // 258
    ProfileInfo::cProfileID_1F6,                                        // 259
    ProfileInfo::cProfileID_075,                                        // 260
    ProfileInfo::cProfileID_0CD,                                        // 261
    ProfileInfo::cProfileID_0CE,                                        // 262
    ProfileInfo::cProfileID_117,                                        // 263
    ProfileInfo::cProfileID_07E,                                        // 264
    ProfileInfo::cProfileID_FloorGyration,                              // 265
    ProfileInfo::cProfileID_09E,                                        // 266
    ProfileInfo::cProfileID_31F,                                        // 267
    ProfileInfo::cProfileID_11B,                                        // 268
    ProfileInfo::cProfileID_0D0,                                        // 269
    ProfileInfo::cProfileID_2FF,                                        // 270
    ProfileInfo::cProfileID_093,                                        // 271
    ProfileInfo::cProfileID_094,                                        // 272
    ProfileInfo::cProfileID_095,                                        // 273
    ProfileInfo::cProfileID_0A2,                                        // 274
    ProfileInfo::cProfileID_062,                                        // 275
    ProfileInfo::cProfileID_229,                                        // 276
    ProfileInfo::cProfileID_197,                                        // 277
    ProfileInfo::cProfileID_0DC,                                        // 278
    ProfileInfo::cProfileID_198,                                        // 279
    ProfileInfo::cProfileID_05C,                                        // 280
    ProfileInfo::cProfileID_199,                                        // 281
    ProfileInfo::cProfileID_278,                                        // 282
    ProfileInfo::cProfileID_ElasticKinokoParent,                        // 283
    ProfileInfo::cProfileID_0CB,                                        // 284
    ProfileInfo::cProfileID_0CC,                                        // 285
    ProfileInfo::cProfileID_Bubble,                                     // 286
    ProfileInfo::cProfileID_166,                                        // 287
    ProfileInfo::cProfileID_2F4,                                        // 288
    ProfileInfo::cProfileID_Burner,                                     // 289
    ProfileInfo::cProfileID_0E1,                                        // 290
    ProfileInfo::cProfileID_014,                                        // 291
    ProfileInfo::cProfileID_0E2,                                        // 292
    ProfileInfo::cProfileID_0E3,                                        // 293
    ProfileInfo::cProfileID_0E5,                                        // 294
    ProfileInfo::cProfileID_0E4,                                        // 295
    ProfileInfo::cProfileID_Lemmy,                                      // 296
    ProfileInfo::cProfileID_031,                                        // 297
    ProfileInfo::cProfileID_161,                                        // 298
    ProfileInfo::cProfileID_167,                                        // 299
    ProfileInfo::cProfileID_168,                                        // 300
    ProfileInfo::cProfileID_1FE,                                        // 301
    ProfileInfo::cProfileID_BunW3,                                      // 302
    ProfileInfo::cProfileID_303,                                        // 303
    ProfileInfo::cProfileID_0E9,                                        // 304
    ProfileInfo::cProfileID_29E,                                        // 305
    ProfileInfo::cProfileID_162,                                        // 306
    ProfileInfo::cProfileID_0EA,                                        // 307
    ProfileInfo::cProfileID_0E7,                                        // 308
    ProfileInfo::cProfileID_0E8,                                        // 309
    ProfileInfo::cProfileID_29F,                                        // 310
    ProfileInfo::cProfileID_037,                                        // 311
    ProfileInfo::cProfileID_05D,                                        // 312
    ProfileInfo::cProfileID_323,                                        // 313
    ProfileInfo::cProfileID_0EB,                                        // 314
    ProfileInfo::cProfileID_0E6,                                        // 315
    ProfileInfo::cProfileID_099,                                        // 316
    ProfileInfo::cProfileID_BunW5,                                      // 317
    ProfileInfo::cProfileID_BubbleSync,                                 // 318
    ProfileInfo::cProfileID_0B2,                                        // 319
    ProfileInfo::cProfileID_292,                                        // 320
    ProfileInfo::cProfileID_22A,                                        // 321
    ProfileInfo::cProfileID_325,                                        // 322
    ProfileInfo::cProfileID_187,                                        // 323
    ProfileInfo::cProfileID_0B3,                                        // 324
    ProfileInfo::cProfileID_19E,                                        // 325
    ProfileInfo::cProfileID_19D,                                        // 326
    ProfileInfo::cProfileID_0A7,                                        // 327
    ProfileInfo::cProfileID_19F,                                        // 328
    ProfileInfo::cProfileID_236,                                        // 329
    ProfileInfo::cProfileID_0B4,                                        // 330
    ProfileInfo::cProfileID_237,                                        // 331
    ProfileInfo::cProfileID_238,                                        // 332
    ProfileInfo::cProfileID_239,                                        // 333
    ProfileInfo::cProfileID_20D,                                        // 334
    ProfileInfo::cProfileID_20F,                                        // 335
    ProfileInfo::cProfileID_2A2,                                        // 336
    ProfileInfo::cProfileID_2A1,                                        // 337
    ProfileInfo::cProfileID_144,                                        // 338
    ProfileInfo::cProfileID_0F1,                                        // 339
    ProfileInfo::cProfileID_1A0,                                        // 340
    ProfileInfo::cProfileID_326,                                        // 341
    ProfileInfo::cProfileID_23A,                                        // 342
    ProfileInfo::cProfileID_23B,                                        // 343
    ProfileInfo::cProfileID_249,                                        // 344
    ProfileInfo::cProfileID_0F3,                                        // 345
    ProfileInfo::cProfileID_304,                                        // 346
    ProfileInfo::cProfileID_0F5,                                        // 347
    ProfileInfo::cProfileID_0F8,                                        // 348
    ProfileInfo::cProfileID_0F4,                                        // 349
    ProfileInfo::cProfileID_096,                                        // 350
    ProfileInfo::cProfileID_1F9,                                        // 351
    ProfileInfo::cProfileID_2A4,                                        // 352
    ProfileInfo::cProfileID_032,                                        // 353
    ProfileInfo::cProfileID_0FA,                                        // 354
    ProfileInfo::cProfileID_FloorHoleDokan,                             // 355
    ProfileInfo::cProfileID_0FB,                                        // 356
    ProfileInfo::cProfileID_28D,                                        // 357
    ProfileInfo::cProfileID_0B0,                                        // 358
    ProfileInfo::cProfileID_0FC,                                        // 359
    ProfileInfo::cProfileID_0B1,                                        // 360
    ProfileInfo::cProfileID_015,                                        // 361
    ProfileInfo::cProfileID_305,                                        // 362
    ProfileInfo::cProfileID_327,                                        // 363
    ProfileInfo::cProfileID_23C,                                        // 364
    ProfileInfo::cProfileID_1C1,                                        // 365
    ProfileInfo::cProfileID_016,                                        // 366
    ProfileInfo::cProfileID_16B,                                        // 367
    ProfileInfo::cProfileID_Morton,                                     // 368
    ProfileInfo::cProfileID_1B4,                                        // 369
    ProfileInfo::cProfileID_1A3,                                        // 370
    ProfileInfo::cProfileID_097,                                        // 371
    ProfileInfo::cProfileID_100,                                        // 372
    ProfileInfo::cProfileID_064,                                        // 373
    ProfileInfo::cProfileID_321,                                        // 374
    ProfileInfo::cProfileID_322,                                        // 375
    ProfileInfo::cProfileID_049,                                        // 376
    ProfileInfo::cProfileID_03B,                                        // 377
    ProfileInfo::cProfileID_32C,                                        // 378
    ProfileInfo::cProfileID_32F,                                        // 379
    ProfileInfo::cProfileID_13C,                                        // 380
    ProfileInfo::cProfileID_17A,                                        // 381
    ProfileInfo::cProfileID_293,                                        // 382
    ProfileInfo::cProfileID_Wendy,                                      // 383
    ProfileInfo::cProfileID_24E,                                        // 384
    ProfileInfo::cProfileID_Ludwig,                                     // 385
    ProfileInfo::cProfileID_18D,                                        // 386
    ProfileInfo::cProfileID_331,                                        // 387
    ProfileInfo::cProfileID_103,                                        // 388
    ProfileInfo::cProfileID_Roy,                                        // 389
    ProfileInfo::cProfileID_09B,                                        // 390
    ProfileInfo::cProfileID_09D,                                        // 391
    ProfileInfo::cProfileID_UnderwaterKoopaJr,                          // 392
    ProfileInfo::cProfileID_16D,                                        // 393
    ProfileInfo::cProfileID_330,                                        // 394
    ProfileInfo::cProfileID_LiftZenStar,                                // 395
    ProfileInfo::cProfileID_104,                                        // 396
    ProfileInfo::cProfileID_131,                                        // 397
    ProfileInfo::cProfileID_132,                                        // 398
    ProfileInfo::cProfileID_UnderwaterKoopaJr,                          // 399
    ProfileInfo::cProfileID_061,                                        // 400
    ProfileInfo::cProfileID_ShuffleBlockMgr,                            // 401
    ProfileInfo::cProfileID_2EF,                                        // 402
    ProfileInfo::cProfileID_Iggy,                                       // 403
    ProfileInfo::cProfileID_157,                                        // 404
    ProfileInfo::cProfileID_042,                                        // 405
    ProfileInfo::cProfileID_BossKK,                                     // 406
    ProfileInfo::cProfileID_BgActorYukaMario,                           // 407
    ProfileInfo::cProfileID_MiniGameKinopio,                            // 408
    ProfileInfo::cProfileID_16E,                                        // 409
    ProfileInfo::cProfileID_0FE,                                        // 410
    ProfileInfo::cProfileID_Kameck,                                     // 411
    ProfileInfo::cProfileID_KameckDemo,                                 // 412
    ProfileInfo::cProfileID_1CB,                                        // 413
    ProfileInfo::cProfileID_KokoopaShipLemmy,                           // 414
    ProfileInfo::cProfileID_KokoopaShipMorton,                          // 415
    ProfileInfo::cProfileID_WakiSearchMagKiller,                        // 416
    ProfileInfo::cProfileID_KokoopaShipLarry,                           // 417
    ProfileInfo::cProfileID_KokoopaShipWendy,                           // 418
    ProfileInfo::cProfileID_KokoopaShipIggy,                            // 419
    ProfileInfo::cProfileID_KokoopaShipRoy,                             // 420
    ProfileInfo::cProfileID_KokoopaShipLudwig,                          // 421
    ProfileInfo::cProfileID_13D,                                        // 422
    ProfileInfo::cProfileID_MiniGameMgr,                                // 423
    ProfileInfo::cProfileID_KokoopaShipWarpCannon,                      // 424
    ProfileInfo::cProfileID_107,                                        // 425
    ProfileInfo::cProfileID_1D2,                                        // 426
    ProfileInfo::cProfileID_11D,                                        // 427
    ProfileInfo::cProfileID_0FF,                                        // 428
    ProfileInfo::cProfileID_043,                                        // 429
    ProfileInfo::cProfileID_03F,                                        // 430
    ProfileInfo::cProfileID_03E,                                        // 431
    ProfileInfo::cProfileID_KoopaJrDemo,                                // 432
    ProfileInfo::cProfileID_BoxingKoopaJr,                              // 433
    ProfileInfo::cProfileID_0A3,                                        // 434
    ProfileInfo::cProfileID_BossKKDemo,                                 // 435
    ProfileInfo::cProfileID_05E,                                        // 436
    ProfileInfo::cProfileID_1D3,                                        // 437
    ProfileInfo::cProfileID_1D3,                                        // 438
    ProfileInfo::cProfileID_0A1,                                        // 439
    ProfileInfo::cProfileID_23D,                                        // 440
    ProfileInfo::cProfileID_284,                                        // 441
    ProfileInfo::cProfileID_294,                                        // 442
    ProfileInfo::cProfileID_210,                                        // 443
    ProfileInfo::cProfileID_11E,                                        // 444
    ProfileInfo::cProfileID_33F,                                        // 445
    ProfileInfo::cProfileID_286,                                        // 446
    ProfileInfo::cProfileID_2A5,                                        // 447
    ProfileInfo::cProfileID_32E,                                        // 448
    ProfileInfo::cProfileID_328,                                        // 449
    ProfileInfo::cProfileID_KameckIceConfig,                            // 450
    ProfileInfo::cProfileID_1C8,                                        // 451
    ProfileInfo::cProfileID_SlotYoshiChibi,                             // 452
    ProfileInfo::cProfileID_148,                                        // 453
    ProfileInfo::cProfileID_149,                                        // 454
    ProfileInfo::cProfileID_010,                                        // 455
    ProfileInfo::cProfileID_KameckWarpPos,                              // 456
    ProfileInfo::cProfileID_05B,                                        // 457
    ProfileInfo::cProfileID_088,                                        // 458
    ProfileInfo::cProfileID_PeachFinalCastleKoopaJr,                    // 459
    ProfileInfo::cProfileID_01D,                                        // 460
    ProfileInfo::cProfileID_01E,                                        // 461
    ProfileInfo::cProfileID_Koopa,                                      // 462
    ProfileInfo::cProfileID_15C,                                        // 463
    ProfileInfo::cProfileID_108,                                        // 464
    ProfileInfo::cProfileID_143,                                        // 465
    ProfileInfo::cProfileID_KoopaDemo,                                  // 466
    ProfileInfo::cProfileID_KoopaShutter,                               // 467
    ProfileInfo::cProfileID_KoopaFireWaki,                              // 468
    ProfileInfo::cProfileID_Peach,                                      // 469
    ProfileInfo::cProfileID_2F0,                                        // 470
    ProfileInfo::cProfileID_1D8,                                        // 471
    ProfileInfo::cProfileID_1D9,                                        // 472
    ProfileInfo::cProfileID_FinalKoopa,                                 // 473
    ProfileInfo::cProfileID_CoinmakiCannon,                             // 474
    ProfileInfo::cProfileID_13E,                                        // 475
    ProfileInfo::cProfileID_202,                                        // 476
    ProfileInfo::cProfileID_FinalKoopaJr,                               // 477
    ProfileInfo::cProfileID_174,                                        // 478
    ProfileInfo::cProfileID_04A,                                        // 479
    ProfileInfo::cProfileID_1B3,                                        // 480
    ProfileInfo::cProfileID_1F8,                                        // 481
    ProfileInfo::cProfileID_21A,                                        // 482
    ProfileInfo::cProfileID_FireBarSync,                                // 483
    ProfileInfo::cProfileID_030,                                        // 484
    ProfileInfo::cProfileID_044,                                        // 485
    ProfileInfo::cProfileID_31A,                                        // 486
    ProfileInfo::cProfileID_24A,                                        // 487
    ProfileInfo::cProfileID_295,                                        // 488
    ProfileInfo::cProfileID_10A,                                        // 489
    ProfileInfo::cProfileID_10B,                                        // 490
    ProfileInfo::cProfileID_PeachFinalCastleKoopaJrLift,                // 491
    ProfileInfo::cProfileID_PeachFinalCastleKoopaJrLiftHmove,           // 492
    ProfileInfo::cProfileID_03A,                                        // 493
    ProfileInfo::cProfileID_UnderwaterKoopaJrRetreatPos,                // 494
    ProfileInfo::cProfileID_020,                                        // 495
    ProfileInfo::cProfileID_1A5,                                        // 496
    ProfileInfo::cProfileID_FinalKoopaDemo,                             // 497
    ProfileInfo::cProfileID_18A,                                        // 498
    ProfileInfo::cProfileID_04B,                                        // 499
    ProfileInfo::cProfileID_300,                                        // 500
    ProfileInfo::cProfileID_013,                                        // 501
    ProfileInfo::cProfileID_301,                                        // 502
    ProfileInfo::cProfileID_114,                                        // 503
    ProfileInfo::cProfileID_232,                                        // 504
    ProfileInfo::cProfileID_233,                                        // 505
    ProfileInfo::cProfileID_0B5,                                        // 506
    ProfileInfo::cProfileID_ShootingStar,                               // 507
    ProfileInfo::cProfileID_101,                                        // 508
    ProfileInfo::cProfileID_155,                                        // 509
    ProfileInfo::cProfileID_156,                                        // 510
    ProfileInfo::cProfileID_ObjPipeDownNG,                              // 511
    ProfileInfo::cProfileID_0A6,                                        // 512
    ProfileInfo::cProfileID_340,                                        // 513
    ProfileInfo::cProfileID_341,                                        // 514
    ProfileInfo::cProfileID_045,                                        // 515
    ProfileInfo::cProfileID_082,                                        // 516
    ProfileInfo::cProfileID_083,                                        // 517
    ProfileInfo::cProfileID_084,                                        // 518
    ProfileInfo::cProfileID_085,                                        // 519
    ProfileInfo::cProfileID_15D,                                        // 520
    ProfileInfo::cProfileID_342,                                        // 521
    ProfileInfo::cProfileID_0DF,                                        // 522
    ProfileInfo::cProfileID_140,                                        // 523
    ProfileInfo::cProfileID_047,                                        // 524
    ProfileInfo::cProfileID_133,                                        // 525
    ProfileInfo::cProfileID_134,                                        // 526
    ProfileInfo::cProfileID_PeachDemo,                                  // 527
    ProfileInfo::cProfileID_343,                                        // 528
    ProfileInfo::cProfileID_2A3,                                        // 529
    ProfileInfo::cProfileID_0AE,                                        // 530
    ProfileInfo::cProfileID_345,                                        // 531
    ProfileInfo::cProfileID_RoyLiftWaki,                                // 532
    ProfileInfo::cProfileID_WendyIcicle,                                // 533
    ProfileInfo::cProfileID_0D5,                                        // 534
    ProfileInfo::cProfileID_0D6,                                        // 535
    ProfileInfo::cProfileID_268,                                        // 536
    ProfileInfo::cProfileID_Spanner,                                    // 537
    ProfileInfo::cProfileID_118,                                        // 538
    ProfileInfo::cProfileID_17B,                                        // 539
    ProfileInfo::cProfileID_051,                                        // 540
    ProfileInfo::cProfileID_267,                                        // 541
    ProfileInfo::cProfileID_04C,                                        // 542
    ProfileInfo::cProfileID_1CE,                                        // 543
    ProfileInfo::cProfileID_KinokoLiftColor,                            // 544
    ProfileInfo::cProfileID_2A0,                                        // 545
    ProfileInfo::cProfileID_2E9,                                        // 546
    ProfileInfo::cProfileID_QuestPrizeItem,                             // 547
    ProfileInfo::cProfileID_0BC,                                        // 548
    ProfileInfo::cProfileID_046,                                        // 549
    ProfileInfo::cProfileID_1EB,                                        // 550
    ProfileInfo::cProfileID_119,                                        // 551
    ProfileInfo::cProfileID_1F7,                                        // 552
    ProfileInfo::cProfileID_16C,                                        // 553
    ProfileInfo::cProfileID_346,                                        // 554
    ProfileInfo::cProfileID_17C,                                        // 555
    ProfileInfo::cProfileID_StaffCreditChibiYoshiABC,                   // 556
    ProfileInfo::cProfileID_StaffRollMgr,                               // 557
    ProfileInfo::cProfileID_PeachFinalCastleKoopaJrDemo,                // 558
    ProfileInfo::cProfileID_1CA,                                        // 559
    ProfileInfo::cProfileID_WendyFloor,                                 // 560
    ProfileInfo::cProfileID_31B,                                        // 561
    ProfileInfo::cProfileID_039,                                        // 562
    ProfileInfo::cProfileID_041,                                        // 563
    ProfileInfo::cProfileID_24D,                                        // 564
    ProfileInfo::cProfileID_Woochan,                                    // 565
    ProfileInfo::cProfileID_0B7,                                        // 566
    ProfileInfo::cProfileID_230,                                        // 567
    ProfileInfo::cProfileID_296,                                        // 568
    ProfileInfo::cProfileID_1C9,                                        // 569
    ProfileInfo::cProfileID_024,                                        // 570
    ProfileInfo::cProfileID_2E3,                                        // 571
    ProfileInfo::cProfileID_2EA,                                        // 572
    ProfileInfo::cProfileID_0DA,                                        // 573
    ProfileInfo::cProfileID_087,                                        // 574
    ProfileInfo::cProfileID_152,                                        // 575
    ProfileInfo::cProfileID_151,                                        // 576
    ProfileInfo::cProfileID_153,                                        // 577
    ProfileInfo::cProfileID_ObjPipeDownGroup,                           // 578
    ProfileInfo::cProfileID_281,                                        // 579
    ProfileInfo::cProfileID_282,                                        // 580
    ProfileInfo::cProfileID_SearchKillerHoudai,                         // 581
    ProfileInfo::cProfileID_SearchMagnumKillerHoudai,                   // 582
    ProfileInfo::cProfileID_SearchMagnumKillerHoudaiDown,               // 583
    ProfileInfo::cProfileID_145,                                        // 584
    ProfileInfo::cProfileID_0F2,                                        // 585
    ProfileInfo::cProfileID_222,                                        // 586
    ProfileInfo::cProfileID_21D,                                        // 587
    ProfileInfo::cProfileID_216,                                        // 588
    ProfileInfo::cProfileID_217,                                        // 589
    ProfileInfo::cProfileID_218,                                        // 590
    ProfileInfo::cProfileID_219,                                        // 591
    ProfileInfo::cProfileID_21F,                                        // 592
    ProfileInfo::cProfileID_299,                                        // 593
    ProfileInfo::cProfileID_29C,                                        // 594
    ProfileInfo::cProfileID_1D4,                                        // 595
    ProfileInfo::cProfileID_32D,                                        // 596
    ProfileInfo::cProfileID_220,                                        // 597
    ProfileInfo::cProfileID_0B6,                                        // 598
    ProfileInfo::cProfileID_2F2,                                        // 599
    ProfileInfo::cProfileID_14B,                                        // 600
    ProfileInfo::cProfileID_1D0,                                        // 601
    ProfileInfo::cProfileID_0EF,                                        // 602
    ProfileInfo::cProfileID_314,                                        // 603
    ProfileInfo::cProfileID_BoxingKoopaJrPostBattleDemo,                // 604
    ProfileInfo::cProfileID_BoxingKoopaJrClownPostBattleDemo,           // 605
    ProfileInfo::cProfileID_17E,                                        // 606
    ProfileInfo::cProfileID_1AC,                                        // 607
    ProfileInfo::cProfileID_351,                                        // 608
    ProfileInfo::cProfileID_IggyRoom,                                   // 609
    ProfileInfo::cProfileID_31C,                                        // 610
    ProfileInfo::cProfileID_1FB,                                        // 611
    ProfileInfo::cProfileID_11C,                                        // 612
    ProfileInfo::cProfileID_089,                                        // 613
    ProfileInfo::cProfileID_08A,                                        // 614
    ProfileInfo::cProfileID_213,                                        // 615
    ProfileInfo::cProfileID_026,                                        // 616
    ProfileInfo::cProfileID_1B8,                                        // 617
    ProfileInfo::cProfileID_0F6,                                        // 618
    ProfileInfo::cProfileID_0F7,                                        // 619
    ProfileInfo::cProfileID_226,                                        // 620
    ProfileInfo::cProfileID_228,                                        // 621
    ProfileInfo::cProfileID_352,                                        // 622
    ProfileInfo::cProfileID_241,                                        // 623
    ProfileInfo::cProfileID_012,                                        // 624
    ProfileInfo::cProfileID_0AF,                                        // 625
    ProfileInfo::cProfileID_29A,                                        // 626
    ProfileInfo::cProfileID_PeachFinalCastleKoopaJrLiftPairObj,         // 627
    ProfileInfo::cProfileID_01F,                                        // 628
    ProfileInfo::cProfileID_272,                                        // 629
    ProfileInfo::cProfileID_115,                                        // 630
    ProfileInfo::cProfileID_116,                                        // 631
    ProfileInfo::cProfileID_0DD,                                        // 632
    ProfileInfo::cProfileID_169,                                        // 633
    ProfileInfo::cProfileID_0F9,                                        // 634
    ProfileInfo::cProfileID_25F,                                        // 635
    ProfileInfo::cProfileID_25D,                                        // 636
    ProfileInfo::cProfileID_261,                                        // 637
    ProfileInfo::cProfileID_298,                                        // 638
    ProfileInfo::cProfileID_1C7,                                        // 639
    ProfileInfo::cProfileID_22D,                                        // 640
    ProfileInfo::cProfileID_16F,                                        // 641
    ProfileInfo::cProfileID_00C,                                        // 642
    ProfileInfo::cProfileID_BubbleRDash,                                // 643
    ProfileInfo::cProfileID_BubbleSyncRDash,                            // 644
    ProfileInfo::cProfileID_09C,                                        // 645
    ProfileInfo::cProfileID_MagnumKillerHoudaiRDash,                    // 646
    ProfileInfo::cProfileID_MagnumKillerHoudaiDownRDash,                // 647
    ProfileInfo::cProfileID_SearchMagnumKillerHoudaiRDash,              // 648
    ProfileInfo::cProfileID_SearchMagnumKillerHoudaiDownRDash,          // 649
    ProfileInfo::cProfileID_1AF,                                        // 650
    ProfileInfo::cProfileID_27E,                                        // 651
    ProfileInfo::cProfileID_0CF,                                        // 652
    ProfileInfo::cProfileID_279,                                        // 653
    ProfileInfo::cProfileID_1D1,                                        // 654
    ProfileInfo::cProfileID_0C4,                                        // 655
    ProfileInfo::cProfileID_240,                                        // 656
    ProfileInfo::cProfileID_2E0,                                        // 657
    ProfileInfo::cProfileID_0DB,                                        // 658
    ProfileInfo::cProfileID_234,                                        // 659
    ProfileInfo::cProfileID_006,                                        // 660
    ProfileInfo::cProfileID_29B,                                        // 661
    ProfileInfo::cProfileID_2F1,                                        // 662
    ProfileInfo::cProfileID_18C,                                        // 663
    ProfileInfo::cProfileID_297,                                        // 664
    ProfileInfo::cProfileID_1B0,                                        // 665
    ProfileInfo::cProfileID_14A,                                        // 666
    ProfileInfo::cProfileID_092,                                        // 667
    ProfileInfo::cProfileID_10C,                                        // 668
    ProfileInfo::cProfileID_048,                                        // 669
    ProfileInfo::cProfileID_MiniGameMgrRDash,                           // 670
    ProfileInfo::cProfileID_0C0,                                        // 671
    ProfileInfo::cProfileID_14C,                                        // 672
    ProfileInfo::cProfileID_2ED,                                        // 673
    ProfileInfo::cProfileID_0FD,                                        // 674
    ProfileInfo::cProfileID_0D1,                                        // 675
    ProfileInfo::cProfileID_063,                                        // 676
    ProfileInfo::cProfileID_344,                                        // 677
    ProfileInfo::cProfileID_127,                                        // 678
    ProfileInfo::cProfileID_090,                                        // 679
    ProfileInfo::cProfileID_0AC,                                        // 680
    ProfileInfo::cProfileID_2E5,                                        // 681
    ProfileInfo::cProfileID_1F5,                                        // 682
    ProfileInfo::cProfileID_122,                                        // 683
    ProfileInfo::cProfileID_246,                                        // 684
    ProfileInfo::cProfileID_247,                                        // 685
    ProfileInfo::cProfileID_SwitchPbuttonRDash,                         // 686
    ProfileInfo::cProfileID_20B,                                        // 687
    ProfileInfo::cProfileID_146,                                        // 688
    ProfileInfo::cProfileID_StaffRollMgrRDash,                          // 689
    ProfileInfo::cProfileID_2E7,                                        // 690
    ProfileInfo::cProfileID_2E8,                                        // 691
    ProfileInfo::cProfileID_124,                                        // 692
    ProfileInfo::cProfileID_02C,                                        // 693
    ProfileInfo::cProfileID_0A0,                                        // 694
    ProfileInfo::cProfileID_182,                                        // 695
    ProfileInfo::cProfileID_09F,                                        // 696
    ProfileInfo::cProfileID_147,                                        // 697
    ProfileInfo::cProfileID_1ED,                                        // 698
    ProfileInfo::cProfileID_LineSpinLiftParentRDash,                    // 699
    ProfileInfo::cProfileID_LineSpinLiftChildRDash,                     // 700
    ProfileInfo::cProfileID_125,                                        // 701
    ProfileInfo::cProfileID_1FD,                                        // 702
    ProfileInfo::cProfileID_310,                                        // 703
    ProfileInfo::cProfileID_12F,                                        // 704
    ProfileInfo::cProfileID_WaterIntermittentPermanentRD3_3,            // 705
    ProfileInfo::cProfileID_130,                                        // 706
    ProfileInfo::cProfileID_12D,                                        // 707
    ProfileInfo::cProfileID_347,                                        // 708
    ProfileInfo::cProfileID_0A4,                                        // 709
    ProfileInfo::cProfileID_SwitchPbuttonNoWallKick,                    // 710
    ProfileInfo::cProfileID_0A5,                                        // 711
    ProfileInfo::cProfileID_1EE,                                        // 712
    ProfileInfo::cProfileID_180,                                        // 713
    ProfileInfo::cProfileID_060,                                        // 714
    ProfileInfo::cProfileID_007,                                        // 715
    ProfileInfo::cProfileID_312,                                        // 716
    ProfileInfo::cProfileID_0C3,                                        // 717
    ProfileInfo::cProfileID_1B7,                                        // 718
    ProfileInfo::cProfileID_0A9,                                        // 719
    ProfileInfo::cProfileID_0AB,                                        // 720
    ProfileInfo::cProfileID_1B1,                                        // 721
    ProfileInfo::cProfileID_2E6,                                        // 722
    ProfileInfo::cProfileID_215                                         // 723
};
static_assert((sizeof(MapActor::cProfileID) / sizeof(MapActor::Profile)) == 724);
