#include <player/PlayerBase.h>

static const sead::Vector3f unused(0.0f, 0.0f, 0.0f);

CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, None)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, Walk)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, Jump)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, Fall)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, Land)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, Crouch)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, SitJump)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, Slip)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, Turn)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, HipAttack)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, Funsui)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, Cloud)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, Cloud2)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, Swim)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, JumpDai)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, PlayerJumpDai)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, WaitJump)
CREATE_STATE_VIRTUAL_ID_BASE(PlayerBase, AnimePlay)
